name:                vulkan-hl
version:             0.1.0.0
github:              "githubuser/vulkan-hl"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/vulkan-hl#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- data-default-class
- linear
- monad-control
- mtl
- text
- uuid
- vector
- vector-sized
- vulkan

library:
  source-dirs: src

executables:
  vulkan-hl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -optl "-Wl,--unresolved-symbols=ignore-in-object-files"
    dependencies:
    - vulkan-hl
    - GLFW-b
    - ansi-terminal
    - monad-loops
    - time
    - lens
    - JuicyPixels

tests:
  vulkan-hl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vulkan-hl
